name: build

on:
  push:
    branches:
      - '**/*'
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-24.04
    steps:
      # https://github.com/actions/checkout
      - name: Checkout the repository
        uses: actions/checkout@v4

      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v4

      - name: Install dependencies
        run: |
          npm ci --prefer-offline

      - name: Check source code formatting
        run: |
          npm run format

      - name: Ensure there are no uncommitted changes
        run: |
          git status --porcelain
          test -z "$(git status --porcelain)"
